etc/provision/setup-privileged.sh
public/cantusdata/views/staticpages.py

fix for #396, remove man-db package in provision

fix hanging on man-db tasks when building on windows

---

public/cantusdata/templates/admin/map_folios.html
public/cantusdata/views/map_folios.py

On admin/map_folios menu, provide a complete list of manuscripts with folio mapping status and option to either map folios or edit map folios.
Updates view logic for edit folio mapping: folio mapping is populated with the last saved folio mapping, rather than default.

Add edit folio mapping functionality

---

README.md

Updating documentation to current tech stack.

---

README.md
app/Dockerfile
app/django-config.sh
docker-compose.yaml

development editing

---

app/public/cantusdata/templates/admin/load_chants.html

center load_chants return button

---

app/public/cantusdata/admin/admin.py

Removes erroneous import chants message

---

nginx/nginx.conf

Sorry for the mess. This is part 2 of #526

Modify nginx to allow new staging dns

---

docker-compose.yaml

Run celery with daemon user

---

app/public/cantusdata/admin/admin.py
app/public/cantusdata/celery.py
app/public/cantusdata/settings.py

Add user friendly view of manuscripts modified in the given task.
Adjust celery results setting for updated django_celery_results
package.

Modify task results admin view

---

app/public/cantusdata/helpers/postprocess_iiif.py
app/public/cantusdata/views/manifest_proxy.py

No postprocessing of Karlsruhe yet

Add postprocessing pipeline for IIIF manifests.

---

.env

Release v3.2-0.9.0

---

app/public/cantusdata/models/manuscript.py

Make UNMAPPED default is_mapped status for manuscripts

---

app/public/cantusdata/helpers/chant_importer.py
app/public/cantusdata/models/chant.py
app/public/cantusdata/views/chant_set.py
nginx/public/node/frontend/public/js/app/manuscript-detail/folio/ChantRecordView.js
nginx/public/node/frontend/public/js/app/manuscript-detail/folio/chant-record.template.html
solr/solr/collection1/conf/schema.xml

Add link to CantusDB in chant detail mode

---

nginx/Dockerfile

I just went ahead and did this because it was pretty simple and helps with increasing the speed of container rebuilds on modifications to javascript. I don't want to close the nginx container build issue because there are still some questions (eg. what's up with those errant node_modules), but this does increase speed.

Refactor nginx container build

---

app/public/cantusdata/admin/admin.py
app/public/cantusdata/models/manuscript.py
app/public/cantusdata/settings.py
app/public/cantusdata/templates/admin/map_folios.html
app/public/cantusdata/templatetags/map_folios.py
app/public/cantusdata/test/core/views/test_folio_set.py
app/public/cantusdata/urls.py
app/public/cantusdata/views/chant_set.py
app/public/cantusdata/views/folio_set.py
app/public/cantusdata/views/map_folios.py
nginx/public/node/frontend/public/js/app/manuscript-detail/DivaView.js
nginx/public/node/frontend/public/js/app/manuscript-detail/NavFolioNumberView.js

Multi folio images

---

nginx/public/node/frontend/public/js/app/manuscript-detail/DivaView.js

Make single image scroll default Diva view

---

app/public/cantusdata/test/core/views/test_folio_set.py
app/public/cantusdata/views/folio_set.py
nginx/public/node/frontend/public/js/app/manuscript-detail/DivaView.js
nginx/public/node/frontend/public/js/app/manuscript-detail/NavFolioNumberView.js
nginx/public/node/frontend/public/js/app/manuscript-detail/folio/FolioView.js
nginx/public/node/frontend/public/js/app/manuscript-detail/nav-folio-number.template.html
nginx/public/node/frontend/public/js/app/models/ManuscriptStateModel.js

Issue 544 update unmapped folio numbers

---

.env

Release v3.2-0.10.0

---

nginx/public/node/frontend/public/css/styles.scss

Reduces overlap between volpiano text syllables by reducing
font. Closes #541.

Reduce volpiano text font

---

app/public/cantusdata/views/map_folios.py

Revert manifest call method in map folios

---

.env

Release v3.2-0.10.1

---

app/public/cantusdata/helpers/chant_importer.py
app/public/cantusdata/management/commands/import_data.py

Allow for a manuscript object to be sent directly to ChantImporter

---

.env

Release v3.2-0.10.2

---

app/public/cantusdata/views/chant_set.py
app/public/cantusdata/views/folio_set.py
nginx/public/node/frontend/public/js/app/manuscript-detail/DivaView.js
nginx/public/node/frontend/public/js/app/manuscript-detail/folio/chant-item.template.html
nginx/public/node/frontend/public/js/app/objects/OpenChantState.js

Double folio view fixes

---

.env

Release v3.2-0.10.3

---

nginx/public/node/frontend/public/js/app/manuscript-detail/folio/chant-record.template.html

Open CantusDB links in new tab

---

nginx/public/node/frontend/public/js/app/manuscript-detail/folio/FolioView.js

Close chant on folio switch

---

README.md

Remove TravisCI & Coveralls from ReadMe

---

nginx/public/node/frontend/public/js/app/search/chant-search/ChantSearchProvider.js
nginx/public/node/frontend/public/js/app/search/chant-search/SearchInputView.js
nginx/public/node/frontend/public/js/app/search/chant-search/search-input.template.html
nginx/public/node/frontend/public/js/app/search/search-result-heading.template.html

Make improvements to volpiano search

---

nginx/public/node/frontend/public/js/app/manuscript-detail/DivaFolioAdvancerView.js
nginx/public/node/frontend/public/js/app/manuscript-detail/diva-folio-advancer.template.html

Add go to first chant nav button

---

nginx/public/node/frontend/public/js/app/search/chant-search/SearchInputView.js

Make volpiano checking regexp global

---

.env

Change release var 3.2-0.11.1

---

nginx/public/node/frontend/public/js/app/routers/RouteController.js

Use Provenance and Siglum for page title element

---

nginx/public/node/frontend/public/js/app/manuscript-detail/ManuscriptDetailPageView.js

Use manuscript id to identify manuscript in manuscript detail page search

---

.env

Update release value

---

app/public/data_dumps/manifests.csv

Closes #319 ... now that we have the IIIF manifest for the images, we can serve this manuscript on Cantus Ultimus!

Add manifest for NL-Uu 406 (3 J 7) to manifests.csv

---

.github/workflows/cd_stage.yml

1. Deploy to stage server with Github Action
2. Triggered by pushes to main branch

Deploy to stage server with Github Action

---

app/public/cantusdata/management/commands/import_data.py

Add missing slash in import_data manuscripts url

---

app/public/cantusdata/templates/admin/load_chants.html
app/public/cantusdata/templates/admin/map_folios.html
app/public/cantusdata/templates/base.html
app/public/cantusdata/templates/missing_manuscript_redirect.html
app/public/cantusdata/templates/require.html

I'm doing some other work that will touch some html files, so I'm creating a PR that just format the current templates so that it's clearer what the substantive changes are when they come...

style: format existing django templates with djlint
