DDMAL/cantus

public/cantusdata/management/commands/import_folio_mapping.py, public/cantusdata/management/commands/refresh_solr.py, public/cantusdata/views/map_folios.py
Revises the map follio (found at /admin/map_folio url) procedure by: 
- Removing the intermediate persistence of a csv with mapping data in the file system when folio mapping is completed through the browser.
- Deduplicated the process of saving mapping data to postgres and re-indexing data in solr (now, database interactions and solr reindexing only take place in commands, rather than in both commands AND the map_folio.py view).
- Simplified the structure of the import_folio_mapping and refresh_solr commands.
=> Revise map folio process

docker-compose.yaml
Changes to docker-compose.yaml mean that build of the app container
will wait until the postgres container has status "healthy". Postgres
container is determined healthy when pg_isready, the Postgres command
that tests whether server is accepting connections, returns a positive
result.
=> Add healthcheck on postgres container to docker-compose.yaml

app/Dockerfile
forgot to take out the reference to wait-for-it from the app Dockerfile
=> Removing reference to `wait-for-it` in `app/Dockerfile`

app/django-config.sh
Running the migrate command results in a complete reindexing of the
Solr backend. Running in background allows access to website while
indexing is completed.
=> Run initial migrate command in background.

nginx/public/python/requirements.txt
Matching django versions in `app/public/requirements.txt` and `nginx/public/python/requirements.txt`
=> Matching django versions in requirements

app/public/cantusdata/admin/admin.py, app/public/cantusdata/templates/admin/load_chants.html, app/public/cantusdata/templates/admin/map_folios.html, app/public/cantusdata/urls.py, app/public/cantusdata/views/load_chants.py
Allows for the bulk of the import chant command to complete
on a thread in the background called from the new intermediate
page view. Solves issue of import chant action timeout in
admin page.
Intermediate solve for #150
=> Add intermediate page after import chant action

app/public/cantusdata/models/manuscript.py, app/public/cantusdata/views/map_folios.py
The manuscript model's save method was re-indexing chants in solr
even if chants had never been loaded. Although the error had no
impact on performance, the error is now avoided.
=> Fixes a django error when saving changes to manuscript objects

.github/workflows/lint_and_test.yml
The Black github action should now check the formatting status of pull requests and fail if files are not linted.
=> Add --check parameter to black github action

README.md
This is required because the celery container depends on the image
build for the app service. Running the docker compose up command
initially will try to pull the app container from a remote repo,
rather than build it locally.
=> Update README to include initial docker compose build step

app/public/cantusdata/fixtures/2_initial_data.json, app/public/cantusdata/management/commands/import_data.py, app/public/cantusdata/management/commands/import_folio_mapping.py, app/public/cantusdata/models/manuscript.py, app/public/cantusdata/templates/admin/map_folios.html, app/public/cantusdata/views/map_folios.py
Adds a PENDING state to the manuscript model for is_mapped,
away from a binary state. This allows for the manuscript mapped
status to show as this interim state while processing on manuscript mapping
completes. This interim status shows on the admin/map_folios page
and the admin view during this time.
=> Add PENDING state to manuscript mapping

app/public/cantusdata/admin/admin.py, app/public/cantusdata/templates/admin/map_folios.html, app/public/cantusdata/views/map_folios.py
Includes these updates:
- Create a new task for each manuscript when multiple manuscripts are selected for chat import in the admin view. Older version created a single task with (potentially) multiple manuscripts.
- Remove confirmation page after kicking off chant importing in the admin view. Confirmation is now given with a green banner in the admin view.
- Remove confirmation page after submitting a folio mapping. After #510, mapping shows as pending on the main map folios page. 
- If folio mapping is pending for a manuscript, returning to the map folios page for that manuscript will no longer show a submit button -- shows a pending message instead. This will keep users from manually submitting a duplicate mapping.
These final changes should close #450 & close #473
=> Update map folios and chant import processes

app/public/cantusdata/admin/admin.py, app/public/cantusdata/tasks.py, app/public/cantusdata/views/map_folios.py
Harmonize argument names in `import_data chants` and `map_folios` task. 
Handle discrepancy in representation of task kwargs in task received status and other task states.
=> Fix 500 error in task status admin view

app/public/cantusdata/helpers/postprocess_iiif.py, app/public/data_dumps/manifests.csv
Postprocessing for the manuscript Tongerloo, B-Gu Hs BKT.006 was
erroneously attributed to NL-Uu 406 (3 J 7). This is fixed here.
=> Fix wrong manuscript in iiif postprocessing

app/Dockerfile, docker-compose.yaml
This slight refactoring of the docker build process makes two adjustments:
1. The `app` image build process is quicker during development and minor code changes, because only (a) critical files for the build process and (b) files that are not otherwise mounted to the container are copied during the build process. Changes to the django codebase do not require an image rebuild.
2. We now mount the django codebase to the `celery` container, rather than relying on it being part of the build. This reduces the possibility that code bases in the `celery` container and `app` container go out of sync. Previously if a change was made to the django codebase and containers were not rebuilt, the update could propagate to the `app` container through the filesystem mount, but would not update in the …
=> Reorder docker builds

app/public/cantusdata/management/commands/import_folio_mapping.py, app/public/cantusdata/views/map_folios.py
Previously, an atomic transaction decorator was used when saving folio mappings in the map folios view to ensure that partially saved folio mappings would be rolled back on failure. 
Now that saving the folio mapping is handled by the celery task queue, the primary database transactions for the map folios process occur in a different function.
=> Move atomic decorator for async map folios task

nginx/public/node/frontend/public/js/app/manuscript-detail/DivaView.js
Two folio navigation search suggestion issues detailed #546:
- Clears previous search suggestions more quickly to end situations where very large numbers of suggestions are shown.
- On submitting, the viewer will navigate to the top search suggestion, rather than the current value of the input box.
Closes #546, with residual search suggestion issues in #564.
=> Fix folio navigation search suggestion peculiarities

app/public/data_dumps/manifests.csv
Fixes broken links to IIIF manifests for the following manuscripts:
- D-FUl Aa 55
- D-W 28 Helmst.
- D-W 29 Helmst.
=> Fix broken IIIF manifests in data_dumps/manifests.csv

app/public/cantusdata/admin/admin.py
Default ordering on manuscript admin view is public manuscripts
first, with a secondary ordering by manuscript name.
Closes #576
=> Change default ordering in manuscript admin view

nginx/public/node/frontend/public/js/app/manuscript-detail/folio/ChantCompositeView.js
Serves as a quick fix to an issue mentioned in #585 : if there are folios with chants on them that, for whatever reason, do not have records in Cantus DB, it would be more accurate to say that "No chant *records*" begin on a given folio than that "No chants" begin on that folio.
=> Change 'no chants' message to refer to chant records

app/public/data_dumps/manifests.csv
Resolves a typo found by @ahankinson in the IIIF manifests data dump.
=> Fix typo in manifest for US-PRu Princeton MS. 245

app/public/cantusdata/management/commands/import_data.py
Previously, a manuscript would have the chants_imported flag be set
to True even if the indexing of chants in solr failed. Since solr
indexing is an integral part of the chant import process, expected
behaviour would be that chants_imported is only set to True if both the
database transactions and solr indexing steps complete successfully.
Closes #571
=> Set chants_imported = True after solr completes

nginx/public/node/frontend/public/js/app/manuscript-detail/folio/ChantRecordView.js, nginx/public/node/frontend/public/js/app/manuscript-detail/folio/chant-record.template.html
The previous version of the Chant view template would not include a link to CantusDB if the chant did not have a CantusID. 
The previous link used an unstable URL to CantusDB. We now use `/node/{node_id}` rather than `/chant/{node_id}` to reference a chant record on Cantus DB.
=> Fix CantusDB link where no Cantus ID

nginx/public/node/frontend/public/js/app/manuscript-detail/DivaView.js
Adjusts how submission of the folio navigation form is handled
based on trigger. When the user triggers by clicking on a search
suggestion, the clicked search suggestion is navigated to. Otherwise,
the first search suggestion is navigated to.
Closes #574
=> Fix behaviour on folio nav search submission

nginx/public/node/frontend/public/js/app/manuscript-detail/folio/ChantRecordView.js, nginx/public/node/frontend/public/js/app/manuscript-detail/folio/chant-record.template.html
Closes #312. 
Makes the following additions/fixes:
- Introduces a stop button to halt midi playback.
- Adjusts behaviour of the play button to prevent multiple simultaneous/overlapping plays.
- Speeds up chant playback.
- Modifies plug-in load process to reduce speed of load time on playback initiation and improve page load consistency.
- Introduces handling of liquescent neumes, flats, and barlines.
- Adds support for browsers using mpeg.
- Removes Play button when no volpiano is available.
- Fixes playback timing to remove note bunching at the beginning of playback.
=> Fixes to MIDI playback

nginx/public/node/frontend/public/js/app/manuscript-detail/folio/ChantRecordView.js, nginx/public/node/frontend/public/js/app/utils/midi-player/Base64binary.js, nginx/public/node/frontend/public/js/app/utils/midi-player/audioDetect.js, nginx/public/node/frontend/public/js/app/utils/midi-player/dom_request_script.js, nginx/public/node/frontend/public/js/app/utils/midi-player/dom_request_xhr.js, nginx/public/node/frontend/public/js/app/utils/midi-player/gm.js, nginx/public/node/frontend/public/js/app/utils/midi-player/loader.js, nginx/public/node/frontend/public/js/app/utils/midi-player/midiPlayer.js, nginx/public/node/frontend/public/js/app/utils/midi-player/plugin.webaudio.js
Closes #629 and #632. 
1. All js functions are added to version control and no longer downloaded via cdn.
2. The ogg/vorbis soundfont is added to version control and no longer served via cdn.
3. A MP3 soundfont of vowels is created and added to version control.
4. Plug-ins are modified for consistent support of webkitAudioContext, a framework used instead of AudioContext in older browsers.
=> Add audio vowel support in Safari & remove CDN dependency

app/public/cantusdata/templates/base.html, nginx/public/node/frontend/public/css/styles.scss, nginx/public/node/frontend/public/js/app/layout/HeaderView.js, nginx/public/node/frontend/public/js/app/layout/ModalView.js, nginx/public/node/frontend/public/js/app/layout/modal.template.html, nginx/public/node/frontend/public/js/app/search/chant-search/AboutVolpianoView.js, nginx/public/node/frontend/public/js/app/search/chant-search/about-volpiano.template.html, nginx/public/node/frontend/public/js/app/search/chant-search/search-input.template.html
This PR partially addresses #633 by creating a pop-up modal for additional information about Volpiano search on Cantus Ultimus. Before that issue is closed, the contents of the pop-up box should be reviewed and revised. 
Some features of this request:
- Creates a modal box that is accessed by a link that appears whenever Volpiano or Volpiano (Literal) search types are selected.
- Adjusts modal view to allow for multiple modals on the same page (Note: Our framework continues to only support opening a single modal at a time).
- Makes visible the "x" button to close all modals.
- Reopens a Search modal when the About Volpiano modal is closed if the search interface was in a modal (ie. if search is accessed from the main navbar rather than the manuscript detail view).
- Provides a draft of …
=> Issue 633 about volpiano popup

nginx/public/node/frontend/public/js/app/manuscript-detail/folio/ChantRecordView.js
Adjusts the logic determining which vowel sound to associate with chant text in cases with two vowels in the same syllable. In particular:
- "y" is pronounced [i]
- "ae" and "oe" are pronounced [ɛ]
- "Qu" + vowel is pronounced as the second vowel
The vowel combination "au" is not included because standard ecclesiastical latin pronunciation pronounces both vowels. In this case, we continue to playback that combination as [a]. 
Closes #651.
=> Adjust vowel pronunciation in chant audio

nginx/public/node/frontend/public/css/styles.scss, nginx/public/node/frontend/public/js/app/manuscript-detail/folio/chant-item.template.html
Closes #650 by:
- wrapping the entire chant accordion div in an anchor tag, opening the chant detail panel
- modifying our customized css to match styling to the older version
=> Make chant accordion header clickable

app/public/data_dumps/manifests.csv
The IIIF manifest for CH-Fco Ms 2 (Fribourg) was not automatically importing, because the siglum in manifests.csv did not match the siglum in Cantus DB.
=> Fix typo for CH-Fco Ms. 2 in manifests.csv

postgres/Dockerfile
The Dockerfile for the postgres container should specify the version of postgres to build from (which is also, of course, the version of postgres being used on the site, which is good to have recorded in version control).
=> Specify version of postgres in Dockerfile

app/public/cantusdata/helpers/source_importer.py, app/public/cantusdata/management/commands/import_data.py, app/public/cantusdata/models/manuscript.py
This PR modifies the manuscript data import process so that manuscript data is obtained (primarily) through CantusDB's API's. 
With this PR, we:
- minimize the use of CantusDB html as a source of manuscript metadata
- obtain source id's from CantusDB for all manuscripts and use those id's, rather than Django's built-in auto-incrementing id, for manuscript objects in the Cantus Ultimus database. As such, this is a partial fix for #652.
The manuscript data import process still uses html parsing to obtain a manuscript's provenance attribute, as this is not currently available through CantusDB's API. Once API changes are implemented, this reliance on html parsing should be removed and the provenance attribute should be obtained through the API.
=> Import manuscript data using CantusDB APIs

app/public/cantusdata/helpers/expandr.py, app/public/cantusdata/helpers/mei_conversion/location_utils.py, app/public/cantusdata/helpers/mei_conversion/pitch_utils.py, app/public/cantusdata/helpers/source_importer.py, app/public/cantusdata/management/commands/generate_public_datadump.py, app/public/cantusdata/management/commands/import_data.py, app/public/cantusdata/management/commands/import_folio_mapping.py, app/public/cantusdata/management/commands/refresh_solr.py, app/public/cantusdata/models/manuscript.py, app/public/cantusdata/signals/solr_sync.py, app/public/cantusdata/test/core/helpers/test_expandr.py, app/public/cantusdata/test/core/views/test_chant.py, app/public/cantusdata/test/core/views/test_concordance.py, app/public/cantusdata/test/core/views/test_folio.py, app/public/cantusdata/test/core/views/test_folio_set.py, app/public/cantusdata/test/core/views/test_manuscript.py, app/public/cantusdata/test/core/views/test_search.py, app/public/cantusdata/test/external/iiif/test_iiif.py, app/public/cantusdata/views/search_notation.py, app/public/cantusdata/views/suggestion.py
Reformats python files to adhere to Black's 2023 stable style. Most of the changes resulting from the style guide update involve removing empty lines and extra parentheses. Some reformatting also occurred on files merged while the repo's formatting test was failing.
This PR also includes a commit that expands on an erroneously truncated comment in the SourceImporter class that I discovered while reviewing Black's reformatting. 
Closes #673.
=> Implement Black 2023 style

nginx/public/node/frontend/public/js/app/manuscript-detail/folio/FolioView.js, nginx/public/node/frontend/public/js/app/objects/OpenChantState.js
This PR changes behaviour of chant panes on the manuscript detail page:
1. When a `chant` parameter is set in a url (eg. `/manuscript/25/?folio[0]=008v&chant=5`), the detail panel for this chant is opened on page load. This allows users to copy and share a url to a specific chant. Closes #653. This reverses the change in #623, which was setting the open chant to `null` and overriding the `chant` parameter in the url.
2. Changes where the state (open/closed) of chants for a  manuscript is saved. Previously, this state was stored in `localStorage`, which maintained these states across multiple browser sessions. This led to multiple chants being open on return visits to a manuscript without a clear reason (see #619; in fact, those chants had just been opened but not closed on previous …
=> Modify open chant state management

nginx/public/node/frontend/public/css/styles.scss, nginx/public/node/frontend/public/js/app/search/chant-search/about-volpiano.template.html
This PR edits the About Volpiano page contents to address the edits recommended in the discussion of #633 .
Some highlights: 
1. A serif typeface is now used in the "Volpiano Dictionary" section to differentiate between `I` and `l`. 
2. The use of hyphens to separate neumes, syllables, and words is added.
3. The explanation of the difference between "Volpiano" and "Volpiano (Literal)" search is expanded and (hopefully) improved.
4. Various typos and unclear phrasings are addressed.
I have commented a section of the page text that I wrote thinking it was true about how the search behaved, only to discover on testing that it isn't true....but I think it probably *should* be true. Will prompt discussion of that elsewhere.
=> Edit About Volpiano page contents

nginx/public/node/frontend/public/js/app/search/chant-search/ChantSearchProvider.js, nginx/public/node/frontend/public/js/app/search/chant-search/SearchInputView.js, nginx/public/node/frontend/public/js/app/search/search-result-heading.template.html, solr/solr/collection1/conf/schema.xml
Fixes #687 and fixes #689. 
Hyphens are a reserved character in solr's query language as the boolean "prohibit" operator (https://solr.apache.org/guide/6_6/the-standard-query-parser.html#TheStandardQueryParser-TheBooleanOperator-). This doesn't work so well with the logic of `Volpiano (Literal)` searches, where hyphens will be included in the search string to differentiate between neumes, syllables, and words. 
This PR modifies a volpiano query by escaping hyphens in the query string before sending the query to the solr query parser. These escape characters are then removed again before the query is displayed as part of the query results. 
The PR also adjusts the filters and tokenizers in the solr schema to allow for single-character volpiano queries. Because of the way tokenizing and …
=> Escape hyphens in volpiano (literal) searches

app/public/cantusdata/helpers/scrapers/concordances.py, app/public/cantusdata/management/commands/import_data.py, app/public/data_dumps/concordances.csv, app/public/data_dumps/manifests.csv
Fixes #678 by importing concordance data from a csv file in `data_dumps`. 
Also makes some adjustments for general code cleanliness in the `import_data` command (eg. using f-strings, removing unused imports, and using python's built-in csv reader for reading csv files.
=> Modify concordance import process and clean import_data commant

nginx/public/node/frontend/public/js/app/routers/RouteController.js
In adding template strings (backtick strings) to the definition of the page title in RouteController.js in #702, I failed to put a `$` ahead of the brackets. This PR fixes that minor issue.
=> Fix template strings from PR #702

app/public/cantusdata/templates/admin/map_folios.html, app/public/cantusdata/views/map_folios.py
Improves or fixes many steps to map folios, back-up previous folio mappings, and import mapping back-ups. Fixes #661. Many of these changes adjust the folio mapping back-up process to account for manuscripts with multiple folios per image, introduced in #555.
This PR makes the following changes/resolves the following issues:
1. The csv map folios export is now named with the manuscript ID so that csv backups for different manuscripts can be easily distinguished.
2. Extra lines in csv back-ups have been removed.
3. Csv back-ups now automatically populate the map folios input boxes upon upload. 
4. The map folios Django view logic has been slightly re-factored to better support imports.
=> Fix map folios backup processes

nginx/public/node/frontend/public/js/app/search/chant-search/ChantSearchProvider.js, nginx/public/node/frontend/public/js/app/search/chant-search/SearchInputView.js, nginx/public/node/frontend/public/js/app/search/chant-search/search-input.template.html
Closes #710. In the course of solving this, #719 was discovered and involves mode search but is out of scope for this PR. 
The PR has two primary elements:
1. The handling of `mode` searches is simplified and improved. Previously, `mode` searches were analyzed so that multi-character queries matched more than the expected number of results (see #710 for more details; for example, selecting `T, Chant in Transposition` from among the search options would match chants with mode `Uncertain` because the query analyzer would yield a `t` token that would match the `t` token generated by the "t" in `Uncertain`). Multi-character modes are now searched as truncated phrases (in quotes `"` with the initial single-character code removed).
2. When returning to a search window after navigating away, a …
=> Fix mode search

.github/workflows/lint_and_test.yml, docker-compose.yaml
Convention with the latest version of docker compose is to use a hyphen as the separator in image names. This commit changes the docker-compose yaml to account for this change.
This PR also updates the repo's run-tests GitHub action to use Docker Compose v2.
=> Update docker-compose image names to new convention

rabbitmq/Dockerfile
Closes #692 by specifying a  version of RabbitMQ to use. The version selected is the latest minor version (as of 29 May 2023) released. EOL for RabbitMQ 3.11 is not currently specified.
=> Specify version of rabbitmq to use for docker container

nginx/Dockerfile, nginx/public/node/frontend/public/css/styles.scss
This PR removes extra scroll bars that had appeared on the manuscript detail view (and in the mean-time removes some extraneous styling from our scss.
This PR also includes a slight re-ordering of the `nginx` container build that slightly reduces build time during development of the front-end. We install the volpiano font before copying the rest of the front-end code into the container so we don't have to re-download the font everytime we change the front-end. 
Closes #677.
Thanks for the debug help @zhannaklimanova
=> Remove extra scroll bars on manuscript detail view

app/public/cantusdata/models/folio.py, app/public/cantusdata/views/folio_set.py, solr/solr/cantus_ultimus_1/conf/schema.xml
The solr query used to find suggestions for the folio navigation search is modified to provide more useful results. We assume that the string typed by the user is the beginning of the folio number they wish to search (after some number of leading zeros) with a wildcard following.
For example, previously if a user typed in 4, they would receive suggestions like 0014r and 0034v when those are less likely that folios like 0041r and 0401r.
This PR introduces an index field that is the folio number stripped of leading zeros. This is then the field searched in order to provide suggestions.
Closes https://github.com/DDMAL/cantus/issues/564
=> Change folio navigation search suggestions

app/django-config.sh, app/public/cantusdata/views/suggestion.py, app/public/requirements.txt, nginx/public/node/frontend/public/js/app/collections/SuggestionCollection.js, nginx/public/node/frontend/public/js/app/search/chant-search/suggestions/SuggestionCollectionView.js, nginx/public/node/frontend/public/js/app/utils/SolrQuery.js, solr/solr/cantus_ultimus_1/conf/schema.xml, solr/solr/cantus_ultimus_1/conf/solrconfig.xml
This PR fixes search suggestions for the `feast`, `office`, and `genre` search. These suggestions are provided both for the global site search (accessed from the "Search" button in the Cantus Ultimus header) and the manuscript-specific search (access from the manuscript detail page). Search suggestions are provided by a facet search.
This PR also provides a (commented out) working configuration for a search suggester that ships with solr. While we don't use a solr suggester for this use case, that configuration is left in the solrconfig.xml file and schema.xml file for potential use in other situations; it was finicky, so I didn't want to delete it entirely. 
Fixes #730. Fixes #716.
Because it is a minor change, this PR also includes …
=> Fix search suggesters

solr/solr/cantus_ultimus_1/conf/schema.xml
Closes #751. Adds manuscript spelling field to the full text search in the solr schema.
=> Include manuscript spelling text in full text search

app/public/data_dumps/manifests.csv
Closes #707. Several BNF iiif manifests were not loading with the `import_data iiif` command because the command requires an exact match between the manuscript siglum in `manifests.csv` and the siglum in the database. This PR updates `manifests.csv` so that the sigla there for BMF manuscripts matches the sigla used by CantusDB/Cantus Ultimus.
=> Fix BNF sigla in manifests.csv

app/public/cantusdata/views/chant.py, app/public/cantusdata/views/concordance.py, app/public/cantusdata/views/folio.py, app/public/cantusdata/views/manuscript.py
This PR changes the class inheritance for the `ChantList`, `ChantDetail`, `FolioList`, `FolioDetail`, `ConcordanceList`, `ConcordanceDetail`, `ManuscriptList` and `ManuscriptDetail` views. `*List` views used to inherit from Django Rest Framework's `ListCreateAPIView` which allowed for both GET and POST requests. `*Detail` views used to inherit from Django Rest Framework's `RetrieveUpdateDestroyAPIView` which allowed GET, PUT, PATCH, and DELETE requests. At this time, only GET requests are required on those endpoints, and other request types had been previously allowed without authentication or verification. The now inherit from `ListAPIView` and `RetrieveAPIView` which only provides GET requests.
This PR closes #721, where a complete inventory of Cantus Ultimus's API endpoints was also …
=> Remove edit functions from API endpoints

nginx/public/node/frontend/public/css/styles.scss, nginx/public/node/frontend/public/js/app/search/chant-search/ChantSearchProvider.js, nginx/public/node/frontend/public/js/app/search/chant-search/SearchInputView.js, nginx/public/node/frontend/public/js/app/search/search-result-heading.template.html
This PR:
- Adds closing quotations to the end of search strings if there is an unclosed quotation in the user-entered search string. Solr errors when there are unclosed quotations (ie. an odd number of quotation marks in the query string). In this case we assume that that user is either still typing, so we close the quotation to show intermediate results, or that the user forgot to close the quotation. 
- Previously, the searched-for query string was enclosed in quotation marks. But, since the search string itself may contain quotation marks, we change the styling. 
Old style:
New style:
- Modifies how we display the query for mode searches by adding a space between modes when multiple modes are searched.
Old style:
New style:
Closes #766.
=> Handle quotation marks in search strings and adjust query result header styling

app/public/cantusdata/settings.py
In getting Release 3.2-0.11.3 working on the staging server, I discovered that with our upgrade to Django 4, there were changes to Django's CSRF protection that require the `CSRF_TRUSTED_ORIGINS` setting in our case. This PR adds that setting. See https://docs.djangoproject.com/en/4.2/releases/4.0/#csrf-trusted-origins-changes-4-0.
=> Add CSRF_TRUSTED_ORIGINS to settings.py

nginx/public/node/frontend/public/js/app/manuscript-detail/folio/ChantItemView.js, nginx/public/node/frontend/public/js/app/manuscript-detail/folio/ChantRecordView.js
Closes #767. Playing audio is stopped when the chant is changed by:
a. Closing the open chant accordion panel;
b. Opening a new chant accordion panel; or
c. Scrolling to a new image.
=> Stop chant audio when chant is changed

README.md, app/public/cantusdata/helpers/scrapers/genre.py, app/public/cantusdata/helpers/scrapers/manuscript.py, app/public/cantusdata/helpers/scrapers/sources.py, app/public/cantusdata/helpers/source_importer.py, app/public/cantusdata/management/commands/import_data.py, app/public/cantusdata/management/commands/normalize_chant_csv.py, nginx/public/node/frontend/public/js/app/manuscript-detail/folio/ChantRecordView.js
This PR changes all urls for CantusDB in the Cantus Ultimus code base from cantus.waterloo.ca to cantusdatabase.org. Also uses https rather than http for all requests to CantusDB.
Although the `/genre` page redirects to `/genres` on NewCantus, this PR changes the url in `helpers/scrapers/genre.py` to go directly to `/genres` rather than through the redirect.
Closes #761 along with https://github.com/DDMAL/cantus-staticpages/pull/5
=> Update links to CantusDB (cantus.waterloo.ca --> cantusdatabase.org)

app/public/cantusdata/renderers/csv_renderer.py, app/public/cantusdata/views/folio_set.py
This PR:
-  adds CSVRenderer for use in Django Rest Framework responses. 
- implements the renderer at the existing `/folio-set/manuscript/<manuscript-id>` endpoint. Requests to this endpoint with a `text/csv` accept header will return a csv.
=> Provide csv export option for folio_set view

nginx/public/node/frontend/public/css/styles.scss, nginx/public/node/frontend/public/js/app/manuscript-detail/folio/chant-record.template.html
Closes some minor outstanding UI bugs.
- Closes #781. If a chant has neither full text nor volpiano available, no horizontal dividing line is displayed in the chant detail panel.
Before: 
After: 
- Closes #739. The horizontal divider between modal headers and contents is now stationary.
Before - notice divline running through "Search"
After:
=> Implement minor UI fixes

nginx/public/node/frontend/public/js/app/manuscript-detail/folio/ChantRecordView.js
=> Check whether MIDI.sources is undefined before disconnecting

app/public/cantusdata/templates/missing_manuscript_redirect.html, app/public/cantusdata/test/core/views/test_manuscript.py, app/public/cantusdata/views/manuscript.py
Overrides the default `retrieve` method of the ManuscriptDetailView class so that when a manuscript with the requested ID is not found, a custom `404` page is returned that directs users to the ManuscriptListView (see below).
As mentioned in the function's comment, this is meant to mitigate cases where a link to a specific manuscript was published before manuscripts in Cantus Ultimus had stable ID's.
Closes #802 
Custom 404 Page
https://user-images.githubusercontent.com/11023634/284639619-89ed0747-a41a-46ae-82f8-a69cdda4b741.png
=> Redirect to ManuscriptListView when manuscript is not found

nginx/public/node/frontend/public/js/app/manuscript-detail/DivaView.js, nginx/public/node/frontend/public/js/app/manuscript-detail/ManuscriptDetailPageView.js, nginx/public/node/frontend/public/js/app/manuscript-detail/manuscript-info.template.html
This PR adds information about the source and licensing for images used on Cantus Ultimus to the "Manuscript Info" sidebar on the Manuscript Detail view. 
IIIF manifests conforming to the Presentation API v 2 may have `attribution`, `license`, and `logo` attributes that contain an attribution statement, a link to image licensing information, and a link to a logo of the providing institution, respectively. The contents of the `attribution` attribute must be shown, while showing the other two are optional. This PR opts to show any of the three that are available. 
The associated issue #786 references a `requiredStatement` field. This was introduced with the IIIF Presentation API v 3. No manifests currently on Cantus Ultimus use v 3 of the API, and Diva does not currently support v 3, so …
=> Add IIIF attribution and licence information to "Manuscript Info" sidebar

app/public/cantusdata/helpers/source_importer.py
Revises the `SourceImporter` helper used during the source import process to use Cantus DB's new provenance api to get the name of a source's provenance. This eliminates the need to parse html from CantusDB to get Provenance name, and therefore now at any point in the source import process.
Closes #808.
=> Use CantusDB's provenance json api during source import process

nginx/nginx.conf
Updates `nginx.conf` to remove the need for nested location blocks. 
Requests to the Cantus Ultimus server are directed to cantaloupe if of the form `cantus[.staging].simssa.ca/iiif` or `cantus[.staging].simssa.ca/iiif/2`. The first case (sans `/2`) captures the case of uri's to the Cantus Ultimus IIIF server (for example, those we've put in the Gottschalk reconstruction's manifest). The second case (with `/2`) captures internal redirects generated by cantaloupe.
=> Update nginx.conf for cantaloupe redirects (without nested location blocks)

app/public/cantusdata/helpers/mei_processing/mei_parser.py, app/public/cantusdata/test/core/helpers/mei_processing/test_mei_parser.py
OMR Search enables searching of sequences of intervals and contours both within neumes and between neumes. The version of MEIParser introduced in #806 calculated only intra-neume intervals and contours. This PR adds the calculation of inter-neume intervals and contours to the parser.
This PR also adds some typing to the test suite to conform with `--strict` checking by mypy and some additional subtests of MEIParser.
=> Update MEIParser to include intervals and contours between neumes & syllables

nginx/public/node/frontend/public/js/app/search/chant-search/SearchResultCollectionView.js, nginx/public/node/frontend/public/js/app/search/chant-search/SearchResultItemView.js, nginx/public/node/frontend/public/js/app/search/chant-search/search-result-collection.template.html, nginx/public/node/frontend/public/js/app/search/chant-search/search-result-item.template.html
When `manuscript` is an additional field returned by search (in other words, when the search is not filtered by the manuscript), make it the first column in the search results. This currently applies to the search results obtained in the Search modal window, but not in the search on the manuscript detail page, the latter being already filtered by the manuscript being shown.
Closes #844
=> Make `manuscript` column first in multi-manuscript search results

nginx/public/node/frontend/public/js/app/manuscript-detail/folio/chant-record.template.html, nginx/public/node/frontend/public/js/app/search/chant-search/ChantSearchProvider.js, nginx/public/node/frontend/public/js/app/search/chant-search/SearchResultCollectionView.js, nginx/public/node/frontend/public/js/app/search/chant-search/SearchResultItemView.js, nginx/public/node/frontend/public/js/app/search/chant-search/search-result-collection.template.html, nginx/public/node/frontend/public/js/app/search/chant-search/search-result-item.template.html, solr/solr/cantus_ultimus_1/conf/schema.xml
Makes Cantus ID's searchable in Cantus Ultimus. Also, on the chant metadata panel, makes the Cantus ID (if it exists) into a clickable link to Cantus Index.
Closes #816. 
Note that #820 is still relevant here...this does not change what fields are show in the results, which means that while CantusID's can be searched after this PR, Cantus ID will not currently show up in the results table, just on the chant detail panel that accordions open upon navigating to the chant.
=> Make Cantus ID searchable

app/public/cantusdata/helpers/mei_processing/mei_parser.py, app/public/cantusdata/helpers/mei_processing/mei_parsing_types.py, app/public/cantusdata/helpers/mei_processing/mei_tokenizer.py, app/public/cantusdata/test/core/helpers/mei_processing/test_mei_parser.py, app/public/cantusdata/test/core/helpers/mei_processing/test_mei_tokenizer.py, poetry.lock, pyproject.toml
This PR makes a number of changes to `helpers/mei_processing/mei_parser.py` and `helpers/mei_processing/mei_tokenizer.py` and their associated type and test files. These changes include:
- refactoring `MEITokenizer` so that we no longer return two different types of ngram documents (one on the neume level and one on the neume component level) but a single type of ngram document. This single type always includes pitch (and therefore contour and interval) information and will also include neume names if the ngram coincides with a set of complete neumes. This refactoring ensures that we can: 1. return pitch information when a neume name is queried; and 2.  we don't have multiple ngrams (one containing pitch information and one containing neume names) for the same set of pitches.
- removing …
=> Update MEI parsing and creation of OMR search tokens

app/public/cantusdata/helpers/mei_processing/mei_parsing_types.py, app/public/cantusdata/helpers/mei_processing/mei_tokenizer.py, app/public/cantusdata/helpers/search_utils.py, app/public/cantusdata/test/core/helpers/mei_processing/test_mei_tokenizer.py, app/public/cantusdata/test/core/helpers/test_search_utils.py, app/public/cantusdata/test/core/views/test_search_notation_view.py, app/public/cantusdata/views/search_notation.py, solr/solr/cantus_ultimus_1/conf/schema.xml, solr/solr/cantus_ultimus_1/conf/solrconfig.xml
The `SearchNotation` view was refactored and reorganized for clarity and to include type annotations and a variety of checks on the passed parameters. Searches for neume names, both transposed and fixed pitches, and contour are supported. The `text` and `incipit` searches were removed because they are handled by the normal search view. The `interval` search was removed for now because it has not yet been implemented in the MEI parsing and indexing. An issue to add it back has been created (#875).
One odd thing is that on the old version of OMR search, `Pitch` search did not search transpositions of pitches, while `Pitch (Invariant)` search did. See images. To me, that seems the wrong way around. I've kept this labeling that way in this PR, but I'm curious for @lucasmarchd01 and …
=> Rewrite SearchNotationView for new OMR search

.github/dependabot.yml, app/public/cantusdata/settings.py, docker-compose.yaml
This PR addresses two minor issues:
1. Fixes an issue in how the "DEVELOPMENT" environment variable was read in the django settings.py file. The result of the `os.environ.get` call is alway a string, so we need to check it against a string in order to get a boolean value.
2. It has dependabot check for updates monthly rather than weekly. Since we look for patch updates, this was resulting in a lot of dependabot PR's being opened and then closed much more frequently than we actually update our servers. 
It also removes an unused `version` parameter in the `docker-compose.yml` file.
=> Settings and dependabot fixes

README.md, app/public/cantusdata/admin/admin.py, app/public/cantusdata/test/core/views/test_search_notation_view.py, app/public/cantusdata/views/search_notation.py, nginx/public/node/frontend/public/js/app/collections/SearchNotationResultCollection.js, nginx/public/node/frontend/public/js/app/search/omr-search/OMRSearchProvider.js
Closes #876.
This PR:
- adds some additional metadata about an OMR (Notation) search to the frontend: the number of results found and the "query" in a displayable form
- return the integer semitones field of omr search documents
- refactors the names of some query types
- requires spaces between terms in contour search to conform to other omr search types
The PR also updates the README with instructions for enabling OMR search on a manuscript.
=> Restore OMR search frontend

app/public/cantusdata/management/commands/index_manuscript_mei.py, app/public/cantusdata/test/core/helpers/mei_processing/test_mei_files/123723/cdn-hsmu-m2149l4_999r.mei, app/public/cantusdata/test/core/management/commands/test_index_manuscript_mei.py
Closes #889.
When chants end on a folio where no other chants begin, the folio does not exist in CantusDB but does have an MEI file. Folio A14r in Salzinnes is a good example of this: 
There is only one line of music on this folio -- the ending of a [chant](https://cantusdatabase.org/chant/272660) that begins on the previous folio. Thus, we have no chant in CantusDB that has folio "A14r", but we do have a MEI file for folio "A14r" from the OMR process. 
This PR modifies the index_manuscript_mei command to create a folio in such cases (we check that it's a "real" folio by making sure the mei file follows a naming convention and then create the folio if it doesn't exist). The user is alerted to this, and then must manually add the image_uri to the folio (either through the admin panel or …
=> Create previously non-existent folios during mei indexing

nginx/public/node/frontend/public/css/styles.scss, nginx/public/node/frontend/public/js/app/manuscript-detail/folio/ChantRecordView.js, nginx/public/node/frontend/public/js/app/manuscript-detail/folio/chant-record.template.html
'On' state colour is black, same as the page header.
Wasn't sure where the most appropriate place in styles.scss would be for the slider. Put it at the end.
=> Issue #919 Changed 'Treble Voice' button to switch

app/public/data_dumps/manifests.csv
changed https://iiif.archivelab.org/iiif/3/McGillLibrary-rbsc_ms-medieval-073-18802/manifest.json to https://iiif.archive.org/iiif/3/McGillLibrary-rbsc_ms-medieval-073-18802/manifest.json
=> updated base domain for IA IIIF URL (removed 'lab')
